package com.sass.module;

import com.sass.ast.SassNode;
import com.sass.ast.css.modifiable.ModifiableCssStylesheet;
import com.sass.callable.Callable;
import com.sass.value.Value;
import org.jspecify.annotations.Nullable;

import java.net.URI;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;

/**
 * A loaded Sass module, produced by evaluating a stylesheet.
 *
 * <p>A module exposes the variables, functions, and mixins defined in its source
 * file. It also holds the CSS output generated by that file.</p>
 *
 * <p>Ported from {@code lib/src/module.dart}.</p>
 */
public final class Module {

    private final @Nullable URI url;
    private final Map<String, Value> variables;
    private final Map<String, Callable> functions;
    private final Map<String, Callable> mixins;
    private final ModifiableCssStylesheet css;

    public Module(
            @Nullable URI url,
            Map<String, Value> variables,
            Map<String, Callable> functions,
            Map<String, Callable> mixins,
            ModifiableCssStylesheet css) {
        this.url = url;
        this.variables = new HashMap<>(variables);
        this.functions = new HashMap<>(functions);
        this.mixins = new HashMap<>(mixins);
        this.css = css;
    }

    public @Nullable URI getUrl() {
        return url;
    }

    /** Returns the module's exposed variables (name -> value, no $ prefix). */
    public Map<String, Value> getVariables() {
        return variables;
    }

    /** Returns the module's exposed functions. */
    public Map<String, Callable> getFunctions() {
        return functions;
    }

    /** Returns the module's exposed mixins. */
    public Map<String, Callable> getMixins() {
        return mixins;
    }

    /** Returns the CSS output generated by this module. */
    public ModifiableCssStylesheet getCss() {
        return css;
    }

    /**
     * Returns a filtered/prefixed view of this module for @forward with show/hide/prefix.
     */
    public Module forward(
            @Nullable Set<String> shownVariables,
            @Nullable Set<String> shownMixinsAndFunctions,
            @Nullable Set<String> hiddenVariables,
            @Nullable Set<String> hiddenMixinsAndFunctions,
            @Nullable String prefix) {
        var filteredVars = filterMap(variables, shownVariables, hiddenVariables, prefix);
        var filteredFuncs = filterMap(functions, shownMixinsAndFunctions, hiddenMixinsAndFunctions, prefix);
        var filteredMixins = filterMap(mixins, shownMixinsAndFunctions, hiddenMixinsAndFunctions, prefix);
        return new Module(url, filteredVars, filteredFuncs, filteredMixins, css);
    }

    private static <T> Map<String, T> filterMap(
            Map<String, T> source,
            @Nullable Set<String> shown,
            @Nullable Set<String> hidden,
            @Nullable String prefix) {
        var result = new HashMap<String, T>();
        for (var entry : source.entrySet()) {
            var name = entry.getKey();
            if (shown != null && !shown.contains(name)) continue;
            if (hidden != null && hidden.contains(name)) continue;
            var outputName = prefix != null ? prefix + name : name;
            result.put(outputName, entry.getValue());
        }
        return result;
    }
}
